# Generated by Django 4.2.4 on 2023-08-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_up', models.DateTimeField(auto_now_add=True)),
                ('update_up', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(upload_to='logo')),
                ('phone1', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('twiter', models.URLField()),
                ('facebook', models.URLField()),
                ('pinterest', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
