# Generated by Django 4.2.4 on 2023-08-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_activate',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='is_activate',
        ),
    ]
